---
title: "Differential expression analysis"
author: "ejjohnson93"
date: "2022-09-28"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Load libraries

```{r, message=FALSE, warning=FALSE}

library(tidyverse)
library(proDA)

```


## Load data

```{r}

# Data
sf_data_norm <- readRDS("./data/sf_data_norm.rds")
plasma_data_norm <- readRDS("./data/plasma_data_norm.rds")


# Pheno
sf_pheno <- readRDS("./data/sf_pheno.rds")
plasma_pheno <- readRDS("./data/plasma_pheno.rds")

```


## Plasma DE analysis 

### Version 1, time as a factor 

```{r}

plasma_design <- plasma_pheno[,c(5,2,1)]
colnames(plasma_design) <- c("name", "day", "horse")
plasma_design$day <- as.factor(plasma_design$day)

```



```{r}

fit <- proDA(as.matrix(plasma_data_norm), design = ~ day + horse, 
             col_data = plasma_design, reference_level = "0") # Manually specified reference level but confirmed its 0 by default

```


`result_names(fit)` can be used to view the names of the possible contrasts. 

```{r}

plasma_day63 <- test_diff(fit, day63)
plasma_day56 <- test_diff(fit, day56)
plasma_day49 <- test_diff(fit, day49)
plasma_day42 <- test_diff(fit, day42)
plasma_day35 <- test_diff(fit, day35)
plasma_day10 <- test_diff(fit, day10)

```

Day 35 and 42 have one sig protein after adjustment each: A0A3Q2HID2 & 	A0A3Q2H659.


### Version 2, time as a continuous variable 
